// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

const (
	Name                   = "ble-desk-lamp"
	DisplayName            = "BLE Desk Lamp"
	Protocol               = "ble"
	SessionMode            = "one-shot"
	SessionOneShotFallback = false
)

type StatusField struct {
	Name                     string `json:"name"`
	SourceCharacteristicUUID string `json:"source_characteristic_uuid"`
	Unit                     string `json:"unit,omitempty"`
	SampleCadence            string `json:"sample_cadence,omitempty"`
	Store                    bool   `json:"store,omitempty"`
}

var StatusFields = []StatusField{}

type CommandDefinition struct {
	Name               string `json:"name"`
	CharacteristicUUID string `json:"characteristic_uuid"`
	Safety             string `json:"safety"`
	ValidationStatus   string `json:"validation_status,omitempty"`
	PayloadHex         string `json:"payload_hex"`
}

var CommandDefinitions = []CommandDefinition{
	{Name: "toggle", CharacteristicUUID: "ff01", Safety: "low-risk-write", ValidationStatus: "observed", PayloadHex: "01"},
}
