// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"time"
)

type StatusSnapshot struct {
	Device      string         `json:"device"`
	Transport   string         `json:"transport"`
	SessionMode string         `json:"session_mode"`
	ObservedAt  string         `json:"observed_at"`
	Telemetry   map[string]any `json:"telemetry"`
}

type CommandResult struct {
	Command            string `json:"command"`
	Transport          string `json:"transport"`
	CharacteristicUUID string `json:"characteristic_uuid"`
	PayloadHex         string `json:"payload_hex"`
	Safety             string `json:"safety"`
	ValidationStatus   string `json:"validation_status,omitempty"`
	DryRun             bool   `json:"dry_run"`
}

type Transport interface {
	Status(context.Context) (StatusSnapshot, error)
	ExecuteCommand(context.Context, CommandDefinition, bool) (CommandResult, error)
}

type ReplayTransport struct{}

func NewReplayTransport() *ReplayTransport {
	return &ReplayTransport{}
}

func (t *ReplayTransport) Status(ctx context.Context) (StatusSnapshot, error) {
	telemetry := map[string]any{}
	for _, field := range StatusFields {
		telemetry[field.Name] = map[string]any{
			"source_characteristic_uuid": field.SourceCharacteristicUUID,
			"sample_cadence":             field.SampleCadence,
			"value":                      nil,
		}
	}
	return StatusSnapshot{
		Device:      DisplayName,
		Transport:   "replay",
		SessionMode: SessionMode,
		ObservedAt:  time.Now().UTC().Format(time.RFC3339),
		Telemetry:   telemetry,
	}, nil
}

func (t *ReplayTransport) ExecuteCommand(ctx context.Context, command CommandDefinition, dryRun bool) (CommandResult, error) {
	return CommandResult{
		Command:            command.Name,
		Transport:          "replay",
		CharacteristicUUID: command.CharacteristicUUID,
		PayloadHex:         command.PayloadHex,
		Safety:             command.Safety,
		ValidationStatus:   command.ValidationStatus,
		DryRun:             dryRun,
	}, nil
}
