// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"

	"ble-session-appliance-pp-cli/internal/device"
	"github.com/spf13/cobra"
)

type rootFlags struct {
	asJSON    bool
	dryRun    bool
	storePath string
}

func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

func Execute() error {
	return RootCmd().Execute()
}

func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	return 1
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:          "ble-session-appliance-pp-cli",
		Short:        "Control BLE Session Appliance over BLE",
		Long:         "Control BLE Session Appliance over BLE using a generated device-native CLI surface.",
		SilenceUsage: true,
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "agent", false, "Output agent-friendly JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Preview device writes without dispatching them")
	rootCmd.PersistentFlags().StringVar(&flags.storePath, "store", "", "Telemetry store path (default: user cache)")
	rootCmd.AddCommand(newCapabilitiesCmd(flags))
	rootCmd.AddCommand(newStatusCmd(flags, device.NewReplayTransport()))
	rootCmd.AddCommand(newSessionCmd(flags, device.NewReplaySession()))
	rootCmd.AddCommand(newTelemetryCmd(flags, device.NewReplayTransport()))
	rootCmd.AddCommand(newDeviceCommandCmd(flags, device.NewReplayTransport(), device.CommandDefinition{Name: "start", CharacteristicUUID: "fd01", Safety: "physical-effect", ValidationStatus: "replay-validated", PayloadHex: "a001"}))
	return rootCmd
}

func writeJSON(cmd *cobra.Command, value any) error {
	enc := json.NewEncoder(cmd.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(value)
}

func newCapabilitiesCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "capabilities",
		Short:       "Show generated BLE capability and safety metadata",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			summary := device.Capabilities()
			if flags.asJSON {
				return writeJSON(cmd, summary)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s capabilities\n", summary.Device)
			fmt.Fprintf(cmd.OutOrStdout(), "protocol: %s\n", summary.Protocol)
			fmt.Fprintf(cmd.OutOrStdout(), "session: %s\n", summary.SessionMode)
			for _, field := range summary.Telemetry {
				fmt.Fprintf(cmd.OutOrStdout(), "telemetry: %s via %s store=%v\n", field.Name, field.SourceCharacteristicUUID, field.Store)
			}
			for _, command := range summary.Commands {
				if command.Callable {
					fmt.Fprintf(cmd.OutOrStdout(), "callable command: %s safety=%s characteristic=%s\n", command.Name, command.Safety, command.CharacteristicUUID)
					continue
				}
				fmt.Fprintf(cmd.OutOrStdout(), "withheld command: %s safety=%s characteristic=%s reason=%s\n", command.Name, command.Safety, command.CharacteristicUUID, command.WithheldReason)
			}
			return nil
		},
	}
}

func newStatusCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	return &cobra.Command{
		Use:         "status",
		Short:       "Read replay-backed device status",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			snapshot, err := transport.Status(cmd.Context())
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, snapshot)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s status\n", snapshot.Device)
			fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", snapshot.Transport)
			fmt.Fprintf(cmd.OutOrStdout(), "session: %s\n", snapshot.SessionMode)
			for _, field := range device.StatusFields {
				value := snapshot.Telemetry[field.Name]
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %v\n", field.Name, value)
			}
			return nil
		},
	}
}

func newDeviceCommandCmd(flags *rootFlags, transport device.Transport, definition device.CommandDefinition) *cobra.Command {
	return &cobra.Command{
		Use:   definition.Name,
		Short: fmt.Sprintf("Replay %s against the device transport", definition.Name),
		RunE: func(cmd *cobra.Command, args []string) error {
			result, err := transport.ExecuteCommand(cmd.Context(), definition, flags.dryRun)
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, result)
			}
			if result.DryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "would write %s to %s for %s\n", result.PayloadHex, result.CharacteristicUUID, result.Command)
				return nil
			}
			fmt.Fprintf(cmd.OutOrStdout(), "replayed %s via %s\n", result.Command, result.Transport)
			return nil
		},
	}
}

func newTelemetryCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	telemetryCmd := &cobra.Command{
		Use:   "telemetry",
		Short: "Capture and read replay-backed telemetry samples",
	}
	telemetryCmd.AddCommand(newTelemetryCaptureCmd(flags, transport))
	telemetryCmd.AddCommand(newTelemetryLatestCmd(flags))
	return telemetryCmd
}

func newTelemetryCaptureCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	return &cobra.Command{
		Use:   "capture",
		Short: "Capture a replay-backed telemetry sample into the local store",
		RunE: func(cmd *cobra.Command, args []string) error {
			snapshot, err := transport.Status(cmd.Context())
			if err != nil {
				return err
			}
			store, err := openTelemetryStore(flags)
			if err != nil {
				return err
			}
			samples, err := store.CaptureStatus(snapshot)
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, samples)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "captured %d telemetry sample(s)\n", len(samples))
			fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
			return nil
		},
	}
}

func newTelemetryLatestCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:         "latest",
		Short:       "Read the latest locally stored telemetry samples",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			store, err := openTelemetryStore(flags)
			if err != nil {
				return err
			}
			samples, err := store.Latest()
			if err != nil {
				return err
			}
			if flags.asJSON {
				return writeJSON(cmd, samples)
			}
			if len(samples) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "no stored telemetry samples")
				fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
				return nil
			}
			for _, sample := range samples {
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %v\n", sample.Field, sample.Value)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "store: %s\n", store.Path())
			return nil
		},
	}
}

func openTelemetryStore(flags *rootFlags) (*device.TelemetryStore, error) {
	storePath := flags.storePath
	if storePath == "" {
		var err error
		storePath, err = device.DefaultTelemetryStorePath("ble-session-appliance-pp-cli")
		if err != nil {
			return nil, err
		}
	}
	return device.OpenTelemetryStore(storePath)
}

func newSessionCmd(flags *rootFlags, session device.Session) *cobra.Command {
	sessionCmd := &cobra.Command{
		Use:   "session",
		Short: "Manage the replay-backed local BLE session runtime",
	}
	sessionCmd.AddCommand(newSessionStatusCmd(flags, session))
	sessionCmd.AddCommand(newSessionStartCmd(flags, session))
	sessionCmd.AddCommand(newSessionStopCmd(flags, session))
	return sessionCmd
}

func newSessionStatusCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:         "status",
		Short:       "Show generated BLE session requirements",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Status(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStartCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start the replay-backed local BLE session runtime",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Start(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStopCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "stop",
		Short: "Stop the replay-backed local BLE session runtime",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Stop(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func writeSessionStatus(cmd *cobra.Command, flags *rootFlags, status device.SessionStatus) error {
	if flags.asJSON {
		return writeJSON(cmd, status)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "%s session\n", status.Device)
	fmt.Fprintf(cmd.OutOrStdout(), "state: %s\n", status.State)
	fmt.Fprintf(cmd.OutOrStdout(), "mode: %s\n", status.Mode)
	fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", status.Transport)
	fmt.Fprintf(cmd.OutOrStdout(), "endpoint: %s %s\n", status.Endpoint.Kind, status.Endpoint.Path)
	fmt.Fprintf(cmd.OutOrStdout(), "runtime: %s\n", status.RuntimeDir)
	fmt.Fprintf(cmd.OutOrStdout(), "token: %v\n", status.TokenPresent)
	fmt.Fprintf(cmd.OutOrStdout(), "one-shot fallback: %v\n", status.OneShotFallback)
	fmt.Fprintf(cmd.OutOrStdout(), "reconnect: %v\n", status.Reconnect)
	fmt.Fprintf(cmd.OutOrStdout(), "notification stream: %v\n", status.NotificationStream)
	for _, reason := range status.Reasons {
		fmt.Fprintf(cmd.OutOrStdout(), "reason: %s\n", reason)
	}
	if status.Detail != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "detail: %s\n", status.Detail)
	}
	return nil
}

func ExecuteWithContext(ctx context.Context) error {
	cmd := RootCmd()
	cmd.SetContext(ctx)
	return cmd.Execute()
}
