// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"time"
)

type SessionStatus struct {
	Device             string   `json:"device"`
	Mode               string   `json:"mode"`
	State              string   `json:"state"`
	Transport          string   `json:"transport"`
	ObservedAt         string   `json:"observed_at"`
	Reasons            []string `json:"reasons,omitempty"`
	OneShotFallback    bool     `json:"one_shot_fallback"`
	Reconnect          bool     `json:"reconnect"`
	NotificationStream bool     `json:"notification_stream"`
	Detail             string   `json:"detail,omitempty"`
}

type Session interface {
	Start(context.Context) (SessionStatus, error)
	Status(context.Context) (SessionStatus, error)
	Stop(context.Context) (SessionStatus, error)
}

type ReplaySession struct{}

func NewReplaySession() *ReplaySession {
	return &ReplaySession{}
}

func (s *ReplaySession) Start(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("started"), nil
}

func (s *ReplaySession) Status(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("not-running"), nil
}

func (s *ReplaySession) Stop(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("stopped"), nil
}

func sessionStatus(state string) SessionStatus {
	return SessionStatus{
		Device:             DisplayName,
		Mode:               SessionMode,
		State:              state,
		Transport:          "replay",
		ObservedAt:         time.Now().UTC().Format(time.RFC3339),
		Reasons:            append([]string(nil), SessionReasons...),
		OneShotFallback:    SessionOneShotFallback,
		Reconnect:          SessionReconnect,
		NotificationStream: SessionNotificationStream,
		Detail:             "replay session scaffold only; live BLE IPC is not enabled in this generated CLI yet",
	}
}
