// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/mark3labs/mcp-go/server"
)

func TestHTTPBindIsLoopback(t *testing.T) {
	t.Parallel()

	cases := []struct {
		addr string
		want bool
	}{
		{addr: "127.0.0.1:7777", want: true},
		{addr: "localhost:7777", want: true},
		{addr: "[::1]:7777", want: true},
		{addr: ":7777", want: false},
		{addr: "0.0.0.0:7777", want: false},
		{addr: "[::]:7777", want: false},
		{addr: "192.168.1.10:7777", want: false},
		{addr: "127.0.0.1", want: false},
	}
	for _, tc := range cases {
		if got := httpBindIsLoopback(tc.addr); got != tc.want {
			t.Fatalf("httpBindIsLoopback(%q) = %v, want %v", tc.addr, got, tc.want)
		}
	}
}

func TestRequireTLSForNonLoopback(t *testing.T) {
	t.Parallel()

	if err := requireTLSForNonLoopback("127.0.0.1:7777", "", ""); err != nil {
		t.Fatalf("loopback without TLS: %v", err)
	}
	if err := requireTLSForNonLoopback("0.0.0.0:7777", "", ""); err == nil {
		t.Fatal("non-loopback without TLS must fail")
	}
	if err := requireTLSForNonLoopback(":7777", "cert.pem", ""); err == nil {
		t.Fatal("empty-host bind without both TLS files must fail")
	}
	if err := requireTLSForNonLoopback("0.0.0.0:7777", "cert.pem", "key.pem"); err != nil {
		t.Fatalf("non-loopback with TLS files: %v", err)
	}
}

func TestRequireHTTPCallerToken(t *testing.T) {
	t.Setenv(httpTokenEnvVar, "")
	if _, err := requireHTTPCallerToken(); err == nil {
		t.Fatal("empty token env must fail")
	}
	t.Setenv(httpTokenEnvVar, "   ")
	if _, err := requireHTTPCallerToken(); err == nil {
		t.Fatal("whitespace token env must fail")
	}
	t.Setenv(httpTokenEnvVar, "shared-secret")
	got, err := requireHTTPCallerToken()
	if err != nil {
		t.Fatalf("set token env: %v", err)
	}
	if got != "shared-secret" {
		t.Fatalf("requireHTTPCallerToken() = %q, want shared-secret", got)
	}
}

func TestRequireBearerAuthRejectsMissingAndWrongTokens(t *testing.T) {
	t.Parallel()

	inner := server.NewStreamableHTTPServer(server.NewMCPServer("auth-proof", "0.0.0-dev"))
	handler := requireBearerAuth("shared-secret", inner)
	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)

	resp, err := http.Post(srv.URL+"/mcp", "application/json", strings.NewReader(`{}`))
	if err != nil {
		t.Fatalf("unauthenticated POST: %v", err)
	}
	body, _ := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("unauthenticated POST status = %d, want 401; body %s", resp.StatusCode, body)
	}

	req, err := http.NewRequest(http.MethodPost, srv.URL+"/mcp", strings.NewReader(`{}`))
	if err != nil {
		t.Fatalf("new request: %v", err)
	}
	req.Header.Set("Authorization", "Bearer wrong-secret")
	req.Header.Set("Content-Type", "application/json")
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("wrong-token POST: %v", err)
	}
	body, _ = io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("wrong-token POST status = %d, want 401; body %s", resp.StatusCode, body)
	}

	req, err = http.NewRequest(http.MethodPost, srv.URL+"/mcp", strings.NewReader(`{}`))
	if err != nil {
		t.Fatalf("new authed request: %v", err)
	}
	req.Header.Set("Authorization", "Bearer shared-secret")
	req.Header.Set("Content-Type", "application/json")
	resp, err = http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("authed POST: %v", err)
	}
	body, _ = io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	if resp.StatusCode == http.StatusUnauthorized {
		t.Fatalf("matching bearer still unauthorized; body %s", body)
	}
}
