// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"strings"

	"github.com/spf13/cobra"
)

const (
	EndpointAnnotation = "pp:endpoint"
	HiddenAnnotation   = "mcp:hidden"
)

type commandKind int

const (
	commandNovel commandKind = iota
	commandEndpoint
	commandFramework
	commandHidden
)

// frameworkCommands are top-level CLI commands the generator emits for every
// printed CLI to support local diagnostics, configuration, and ops. They are
// intentionally NOT exposed as MCP tools: agents do not need to introspect a
// CLI's own version, run its self-doctor, or shell-out to its profile manager
// — these belong on the human-facing CLI surface only. Some (sync, sql,
// search) overlap with typed MCP tools registered elsewhere; without this
// skip list the walker would register colliding shell-out duplicates.
//
// The set must match the canonical framework command list documented in the
// runtime-mirror plan (KTD-3). Adding a new framework command to the
// generator means adding it here too.
var frameworkCommands = map[string]bool{
	"about":         true,
	"agent-context": true,
	"analytics":     true,
	"api":           true,
	"auth":          true,
	"completion":    true,
	"doctor":        true,
	"export":        true,
	"feedback":      true,
	"help":          true,
	"import":        true,
	"load":          true,
	"orphans":       true,
	"profile":       true,
	"reconcile":     true,
	"search":        true,
	"sql":           true,
	"stale":         true,
	"sync":          true,
	"version":       true,
	"which":         true,
	"workflow":      true,
}

func classify(cmd *cobra.Command) commandKind {
	if cmd == nil || cmd.Hidden || isMCPHidden(cmd) {
		return commandHidden
	}
	if endpointID(cmd) != "" {
		return commandEndpoint
	}
	if frameworkCommands[cmd.Name()] {
		return commandFramework
	}
	return commandNovel
}

func endpointID(cmd *cobra.Command) string {
	if cmd == nil || cmd.Annotations == nil {
		return ""
	}
	return strings.TrimSpace(cmd.Annotations[EndpointAnnotation])
}

func isMCPHidden(cmd *cobra.Command) bool {
	if cmd == nil || cmd.Annotations == nil {
		return false
	}
	v := strings.ToLower(strings.TrimSpace(cmd.Annotations[HiddenAnnotation]))
	return v == "true" || v == "1" || v == "yes"
}
