// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"regexp"
	"testing"

	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools mirrors cli.RootCmd, including hand-authored Use placeholders
// the generator never sees. Hosts drop any tool whose property names fall
// outside ^[a-zA-Z0-9_.-]{1,64}$.
func TestMirroredMCPPropertyNames(t *testing.T) {
	s := server.NewMCPServer("mirror-property-names", "test")
	RegisterTools(s)
	valid := regexp.MustCompile(`^[a-zA-Z0-9_.-]{1,64}$`)
	for name, entry := range s.ListTools() {
		if entry == nil || entry.Tool.Meta == nil || entry.Tool.Meta.AdditionalFields["pp:tenant-gate"] != "child-cli" {
			continue
		}
		for prop := range entry.Tool.InputSchema.Properties {
			if !valid.MatchString(prop) {
				t.Errorf("mirrored tool %s property %q does not match %s", name, prop, valid.String())
			}
		}
	}
}
