package cli

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeMiniModule(t *testing.T, root string, files map[string]string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(root, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("module mini\n\ngo 1.22\n"), 0o644))
	for rel, body := range files {
		path := filepath.Join(root, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	}
}

func generatedCLIFile(body string) string {
	return "// Generated by CLI Printing Press. DO NOT EDIT.\npackage cli\n\n" + body
}

// TestFinalizeForceMergeDropsVersionBumpHelperRenamePreserve is validation
// case 2: two-way merge (no synthesized base) of a helper rename. Fresh
// promoted files must win; the dangling old helper call must not ship.
func TestFinalizeForceMergeDropsVersionBumpHelperRenamePreserve(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		"internal/cli/old_helpers.go": generatedCLIFile("func oldHelper() string { return \"old\" }\n"),
		"internal/cli/promoted.go":    generatedCLIFile("func Promoted() string { return oldHelper() }\n"),
		"internal/cli/novel.go":       "package cli\n\nfunc NovelKeep() string { return \"kept\" }\n",
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/cli/helpers.go":  generatedCLIFile("func newHelper() string { return \"new\" }\n"),
		"internal/cli/promoted.go": generatedCLIFile("func Promoted() string { return newHelper() }\n"),
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, false, nil))

	promoted, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "promoted.go"))
	require.NoError(t, err)
	assert.Contains(t, string(promoted), "newHelper",
		"version-bump helper rename must keep the fresh promoted caller")
	assert.NotContains(t, string(promoted), "oldHelper",
		"two-way merge must not preserve a dangling old helper call")
	assert.NoFileExists(t, filepath.Join(freshDir, "internal", "cli", "old_helpers.go"),
		"fresh generation dropped the old helper file; rematch must not rehydrate it")

	novel, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "novel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(novel), "NovelKeep",
		"novel files must survive the build-break rematch")

	require.NoError(t, compileGeneratedTree(freshDir))
}

// TestFinalizeForceMergePreservesCompilingHandEdits is validation case 3 at
// the merge seam: a same-spec templated addition that still builds must
// survive. The generate-level counterpart lives in generate_test.go.
func TestFinalizeForceMergePreservesCompilingHandEdits(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		"internal/cli/root.go": generatedCLIFile("func Execute() {}\n\nfunc HandEdit() string { return \"kept\" }\n"),
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/cli/root.go": generatedCLIFile("func Execute() {}\n"),
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, false, nil))

	got, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "root.go"))
	require.NoError(t, err)
	assert.Contains(t, string(got), "HandEdit",
		"compiling same-spec hand-edits must still be preserved")
	require.NoError(t, compileGeneratedTree(freshDir))
}
