package cli

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// novelWipeSignal carries the evidence that triggered a guard refusal so the
// error message can name the specific risk the operator is about to take.
type novelWipeSignal struct {
	// ManifestNovelFeatures lists novel-feature commands recorded in the
	// existing dir's .printing-press.json. Empty when no manifest exists or
	// the manifest's novel_features array is empty.
	ManifestNovelFeatures []string
	// HandAuthoredFiles lists files under internal/{cli,syncer,store}/ whose
	// header is missing the "Generated by CLI Printing Press" marker. Capped
	// to a handful for readability; HandAuthoredFilesTruncated indicates
	// whether more exist.
	HandAuthoredFiles          []string
	HandAuthoredFilesTruncated bool
}

// detectNovelHandAuthored inspects an existing output directory for evidence
// that destroying it would lose user work. Returns (signal, found).
//
// Two evidence sources, checked in order:
//
//  1. .printing-press.json's novel_features array, written by dogfood when a
//     novel feature command builds successfully.
//  2. Hand-authored .go files under internal/{cli,syncer,store}/ — files
//     whose first 20 lines lack the canonical "Generated by CLI Printing
//     Press" marker. Catches novels in libraries published before
//     novel_features was recorded, novels written outside the dogfood loop,
//     and hand-authored sibling packages (syncer, store) that don't appear
//     in the manifest at all.
//
// found is false (and signal zero) when neither source fires. The caller
// proceeds with the regen-merge-driven happy path. found is true when either
// fires; the caller refuses unless an explicit override flag is set.
func detectNovelHandAuthored(absOut string) (novelWipeSignal, bool) {
	var signal novelWipeSignal

	if features, ok := readManifestNovelFeatures(absOut); ok {
		signal.ManifestNovelFeatures = features
	}

	files, truncated := findHandAuthoredGoFiles(absOut)
	signal.HandAuthoredFiles = files
	signal.HandAuthoredFilesTruncated = truncated

	return signal, len(signal.ManifestNovelFeatures) > 0 || len(signal.HandAuthoredFiles) > 0
}

// readManifestNovelFeatures returns the command list from
// .printing-press.json's novel_features array, or (nil, false) when the
// manifest is missing or has no entries. The full pipeline.CLIManifest is
// deliberately not used here — that package has a heavier dependency
// surface, and we only need a tiny subset for the pre-emit check.
func readManifestNovelFeatures(absOut string) ([]string, bool) {
	manifestPath := filepath.Join(absOut, ".printing-press.json")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, false
	}
	var partial struct {
		NovelFeatures []struct {
			Command string `json:"command"`
		} `json:"novel_features"`
	}
	if err := json.Unmarshal(data, &partial); err != nil {
		fmt.Fprintf(os.Stderr, "warning: .printing-press.json at %s is unparseable (%v); novel-feature signal skipped\n", manifestPath, err)
		return nil, false
	}
	if len(partial.NovelFeatures) == 0 {
		return nil, false
	}
	out := make([]string, 0, len(partial.NovelFeatures))
	for _, nf := range partial.NovelFeatures {
		if nf.Command != "" {
			out = append(out, nf.Command)
		}
	}
	sort.Strings(out)
	return out, len(out) > 0
}

// findHandAuthoredGoFiles walks internal/{cli,syncer,store}/ under absOut
// looking for .go files (excluding _test.go) whose first 20 lines lack the
// "Generated by CLI Printing Press" header. Returns the relative paths
// (forward-slash) capped at handAuthoredFileSampleCap and whether the cap
// truncated the list.
func findHandAuthoredGoFiles(absOut string) ([]string, bool) {
	var found []string
	truncated := false
	for _, sub := range []string{"internal/cli", "internal/syncer", "internal/store"} {
		root := filepath.Join(absOut, sub)
		if _, err := os.Stat(root); err != nil {
			continue
		}
		_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if d.IsDir() {
				return nil
			}
			name := d.Name()
			if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
				return nil
			}
			if fileHasGeneratedMarker(path) {
				return nil
			}
			rel, relErr := filepath.Rel(absOut, path)
			if relErr != nil {
				rel = path
			}
			rel = filepath.ToSlash(rel)
			if len(found) >= handAuthoredFileSampleCap {
				truncated = true
				return filepath.SkipAll
			}
			found = append(found, rel)
			return nil
		})
		if truncated {
			break
		}
	}
	sort.Strings(found)
	return found, truncated
}

// handAuthoredFileSampleCap bounds the file listing in error messages and
// short-circuits the walk once enough evidence is collected. Eight is enough
// to make the refusal feel grounded without producing an unreadable wall.
const handAuthoredFileSampleCap = 8

// fileHasGeneratedMarker scans the first 20 lines for the canonical
// "Generated by CLI Printing Press" marker. Cheaper than the full
// generatedmarker.HasInFile path (which reads the entire file) and matches
// the issue's specified probe depth.
func fileHasGeneratedMarker(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	scanner := bufio.NewScanner(f)
	for i := 0; i < 20 && scanner.Scan(); i++ {
		if strings.Contains(scanner.Text(), "Generated by CLI Printing Press") {
			return true
		}
	}
	return false
}

// novelWipeRefusalError builds the operator-facing error returned when
// --force would destroy hand-authored work and --allow-novel-wipe wasn't
// set. The message names the specific evidence, recommends regen-merge as
// the safer path, and documents the override flag.
func novelWipeRefusalError(absOut string, signal novelWipeSignal) error {
	var b strings.Builder
	fmt.Fprintf(&b, "%s contains hand-authored work that --force would destroy:\n", absOut)
	if len(signal.ManifestNovelFeatures) > 0 {
		fmt.Fprintf(&b, "  .printing-press.json records %d novel feature(s): %s\n",
			len(signal.ManifestNovelFeatures), strings.Join(signal.ManifestNovelFeatures, ", "))
	}
	if len(signal.HandAuthoredFiles) > 0 {
		fmt.Fprintf(&b, "  Hand-authored .go files (no generator header):\n")
		for _, rel := range signal.HandAuthoredFiles {
			fmt.Fprintf(&b, "    %s\n", rel)
		}
		if signal.HandAuthoredFilesTruncated {
			fmt.Fprintf(&b, "    … (more not listed)\n")
		}
	}
	fmt.Fprintf(&b, "\nUse `cli-printing-press regen-merge` for a previewable diff against a fresh-generated tree,\n")
	fmt.Fprintf(&b, "or re-run with `--allow-novel-wipe` to acknowledge the loss and proceed.\n")
	return errors.New(b.String())
}
