package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// generatedHeader matches the marker emitted at the top of every templated
// .go file. Used by the fallback file-probe to skip generator-owned files.
const generatedHeader = `// Copyright 2026 trevin-chow.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
`

func TestDetectNovelHandAuthored_DetectsManifestNovelFeatures(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	manifest := `{
  "schema_version": 1,
  "cli_name": "demo-pp-cli",
  "api_name": "demo",
  "novel_features": [
    {"name": "History top", "command": "history top"},
    {"name": "Favorites suggest", "command": "favorites suggest"}
  ]
}`
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".printing-press.json"), []byte(manifest), 0o644))

	signal, found := detectNovelHandAuthored(dir)
	require.True(t, found)
	assert.ElementsMatch(t, []string{"favorites suggest", "history top"}, signal.ManifestNovelFeatures)
}

func TestDetectNovelHandAuthored_DetectsHandAuthoredFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	for _, sub := range []string{"internal/cli", "internal/syncer", "internal/store"} {
		require.NoError(t, os.MkdirAll(filepath.Join(dir, sub), 0o755))
	}
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/syncer/syncer.go"),
		[]byte("package syncer\nfunc Run() {}\n"),
		0o644,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/store/store.go"),
		[]byte("package store\nfunc Get() {}\n"),
		0o644,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/cli/templated.go"),
		[]byte(generatedHeader+"package cli\n"),
		0o644,
	))

	signal, found := detectNovelHandAuthored(dir)
	require.True(t, found)
	assert.Contains(t, signal.HandAuthoredFiles, "internal/syncer/syncer.go")
	assert.Contains(t, signal.HandAuthoredFiles, "internal/store/store.go")
	assert.NotContains(t, signal.HandAuthoredFiles, "internal/cli/templated.go",
		"files with the generator header must be skipped")
}

func TestDetectNovelHandAuthored_SkipsTestFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal/cli"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/cli/foo_test.go"),
		[]byte("package cli\n"),
		0o644,
	))

	_, found := detectNovelHandAuthored(dir)
	assert.False(t, found, "test files are not user-authored novels")
}

func TestDetectNovelHandAuthored_EmptyManifestNovelFeaturesIsNotASignal(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, ".printing-press.json"),
		[]byte(`{"schema_version": 1, "cli_name": "demo-pp-cli", "novel_features": []}`),
		0o644,
	))
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal/cli"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/cli/templated.go"),
		[]byte(generatedHeader+"package cli\n"),
		0o644,
	))

	_, found := detectNovelHandAuthored(dir)
	assert.False(t, found, "empty novel_features + no hand-authored files must not refuse")
}

func TestDetectNovelHandAuthored_NoManifestAndOnlyGeneratedFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal/cli"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "internal/cli/root.go"),
		[]byte(generatedHeader+"package cli\n"),
		0o644,
	))

	_, found := detectNovelHandAuthored(dir)
	assert.False(t, found,
		"a tree of only generator-marked files (no manifest) must not refuse — that's a fresh print")
}

func TestDetectNovelHandAuthored_CapsHandAuthoredFileList(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal/cli"), 0o755))
	for i := range handAuthoredFileSampleCap + 5 {
		path := filepath.Join(dir, "internal/cli", "novel_"+itoa(i)+".go")
		require.NoError(t, os.WriteFile(path, []byte("package cli\n"), 0o644))
	}

	signal, found := detectNovelHandAuthored(dir)
	require.True(t, found)
	assert.Len(t, signal.HandAuthoredFiles, handAuthoredFileSampleCap)
	assert.True(t, signal.HandAuthoredFilesTruncated)
}

// itoa returns the decimal string for non-negative i.
func itoa(i int) string { return strconv.Itoa(i) }

func TestGenerateCmdForceRefusesNovelWipeWithoutFlag(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	specPath := filepath.Join(dir, "spec.yaml")
	outputDir := filepath.Join(dir, "guardedapp")
	require.NoError(t, os.WriteFile(specPath, []byte(`name: guardedapp
description: Guarded app API
version: 0.1.0
base_url: https://api.example.com
auth:
  type: none
config:
  format: toml
  path: ~/.config/guardedapp-pp-cli/config.toml
resources:
  items:
    description: Manage items
    endpoints:
      list:
        method: GET
        path: /items
        description: List items
`), 0o644))

	runGenerate := func(args ...string) error {
		cmd := newGenerateCmd()
		base := []string{
			"--spec", specPath,
			"--output", outputDir,
			"--validate=false",
			"--force",
		}
		cmd.SetArgs(append(base, args...))
		var out bytes.Buffer
		cmd.SetOut(&out)
		cmd.SetErr(&out)
		return cmd.Execute()
	}

	// Fresh dir: --force is fine; the dir doesn't exist yet so the guard
	// has nothing to detect.
	require.NoError(t, runGenerate("--allow-novel-wipe"))

	// Plant a hand-authored novel feature under internal/cli/.
	novelPath := filepath.Join(outputDir, "internal", "cli", "novel_history.go")
	require.NoError(t, os.WriteFile(novelPath, []byte(`package cli

func novelHistoryFn() string { return "kept" }
`), 0o644))

	// Without --allow-novel-wipe, a second --force must refuse.
	err := runGenerate()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "hand-authored work")
	assert.Contains(t, err.Error(), "regen-merge")
	assert.Contains(t, err.Error(), "--allow-novel-wipe")
	assert.Contains(t, err.Error(), "internal/cli/novel_history.go")

	// Novel file must still be there — the refusal is pre-emit, before any
	// snapshot rename.
	gotNovel, err := os.ReadFile(novelPath)
	require.NoError(t, err)
	assert.Contains(t, string(gotNovel), "novelHistoryFn")

	// With --allow-novel-wipe, the merge path runs and the novel is
	// preserved by regen-merge (NOVEL verdict).
	require.NoError(t, runGenerate("--allow-novel-wipe"))
	gotNovel, err = os.ReadFile(novelPath)
	require.NoError(t, err)
	assert.Contains(t, string(gotNovel), "novelHistoryFn",
		"--allow-novel-wipe defers to the existing regen-merge novel preservation")
}

func TestGenerateCmdForceRefusesNovelWipeFromManifestAlone(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	specPath := filepath.Join(dir, "spec.yaml")
	outputDir := filepath.Join(dir, "manifestguardapp")
	require.NoError(t, os.WriteFile(specPath, []byte(`name: manifestguardapp
description: Manifest guard app API
version: 0.1.0
base_url: https://api.example.com
auth:
  type: none
config:
  format: toml
  path: ~/.config/manifestguardapp-pp-cli/config.toml
resources:
  items:
    description: Manage items
    endpoints:
      list:
        method: GET
        path: /items
        description: List items
`), 0o644))

	// Build a dir whose only signal is a manifest claiming novel features —
	// every .go file carries the generator header so the file-probe would
	// stay silent. This isolates the manifest-driven detection path.
	require.NoError(t, os.MkdirAll(filepath.Join(outputDir, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(
		filepath.Join(outputDir, "internal", "cli", "items.go"),
		[]byte(generatedHeader+"package cli\n"),
		0o644,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(outputDir, ".printing-press.json"),
		[]byte(`{
  "schema_version": 1,
  "cli_name": "manifestguardapp-pp-cli",
  "api_name": "manifestguardapp",
  "novel_features": [{"name": "Recipe top", "command": "recipes top"}]
}`),
		0o644,
	))

	cmd := newGenerateCmd()
	cmd.SetArgs([]string{
		"--spec", specPath,
		"--output", outputDir,
		"--validate=false",
		"--force",
	})
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	err := cmd.Execute()

	require.Error(t, err)
	assert.Contains(t, err.Error(), "recipes top",
		"the refusal must name the novel feature so the operator recognizes what would be lost")
}
