// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"errors"
)

// Advert is a discovered BLE advertisement.
type Advert struct {
	Address      string   `json:"address"`
	Name         string   `json:"name"`
	RSSI         int      `json:"rssi"`
	ServiceUUIDs []string `json:"service_uuids,omitempty"`
}

// ErrLiveUnavailable is returned by every live operation when the binary was
// built without the BLE backend (the default, pure-Go, no-CGO build).
var ErrLiveUnavailable = errors.New("live BLE is not compiled into this binary; rebuild with: go build -tags ble_live ./... (CGO required)")

// ErrDeviceNotFound is returned when a scan finds no matching device.
var ErrDeviceNotFound = errors.New("no matching device found; power it on and close any official app (only one BLE client can connect at a time)")

// ErrVerifyMode is returned by Dial under PRINTING_PRESS_VERIFY: verify must
// never actuate hardware. Hand-authored commands should gate on
// cliutil.IsVerifyEnv() before dialing; this is the backstop.
var ErrVerifyMode = errors.New("live BLE is disabled under verify mode")

// bleBackend is the device-neutral BLE central surface. The live implementation
// (tinygo bluetooth, build tag ble_live) and the pure-Go stub live in separate
// build-tagged files; both provide newBLEBackend and the liveCompiled constant.
type bleBackend interface {
	Scan(ctx context.Context, serviceUUIDs []string) ([]Advert, error)
	Connect(ctx context.Context, address string, serviceUUIDs []string) (Link, error)
}

// Link is a connected device. Write/Read/Subscribe address GATT characteristics
// by UUID, so one connection serves every command and telemetry stream the
// device spec declares. Hand-authored commands obtain a Link via Dial.
type Link interface {
	Write(characteristicUUID string, payload []byte) error
	Read(characteristicUUID string) ([]byte, error)
	Subscribe(characteristicUUID string, handler func([]byte)) error
	Close() error
}

// LiveAvailable reports whether a live BLE backend is compiled into this binary
// (true only when built with -tags ble_live).
func LiveAvailable() bool { return liveCompiled }

// bleBackendFactory opens the BLE backend. It is a var so tests can inject a
// fake backend and exercise LiveTransport without real hardware; production code
// leaves it pointing at the build-tag-selected newBLEBackend.
var bleBackendFactory = newBLEBackend

// DeviceCodec adapts a device whose telemetry frames are not directly usable as
// values (vendor framing, scaling, checksums). Implement it in an operator-owned
// file and register it from an init function (codec = myCodec{}) so the
// generated status command surfaces decoded values; the default (nil codec)
// reports raw hex. Parameterized or stateful control (set a value, hold a
// connection and poll) belongs in hand-authored commands that use Dial + Link.
type DeviceCodec interface {
	DecodeTelemetry(field StatusField, raw []byte) (any, error)
}

// codec is the optional telemetry decoder. nil by default (Tier-1: raw hex).
var codec DeviceCodec
