// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"encoding/hex"
	"testing"
	"time"
)

// fakeLink / fakeBackend exercise LiveTransport without real BLE hardware by
// injecting bleBackendFactory.
type fakeLink struct {
	writes map[string][]byte
	reads  map[string][]byte
	closed bool
}

func (l *fakeLink) Write(uuid string, payload []byte) error {
	if l.writes == nil {
		l.writes = map[string][]byte{}
	}
	l.writes[uuid] = payload
	return nil
}
func (l *fakeLink) Read(uuid string) ([]byte, error)                  { return l.reads[uuid], nil }
func (l *fakeLink) Subscribe(uuid string, handler func([]byte)) error { return nil }
func (l *fakeLink) Close() error                                      { l.closed = true; return nil }

type fakeBackend struct {
	link    *fakeLink
	adverts []Advert
}

func (b *fakeBackend) Scan(ctx context.Context, serviceUUIDs []string) ([]Advert, error) {
	return b.adverts, nil
}
func (b *fakeBackend) Connect(ctx context.Context, address string, serviceUUIDs []string) (bleLink, error) {
	return b.link, nil
}

func withFakeBackend(t *testing.T, be *fakeBackend) {
	t.Helper()
	t.Setenv("PRINTING_PRESS_VERIFY", "") // keep the live path from short-circuiting
	prev := bleBackendFactory
	bleBackendFactory = func() (bleBackend, error) { return be, nil }
	t.Cleanup(func() { bleBackendFactory = prev })
}

func TestLiveTransportExecuteCommandWritesPayload(t *testing.T) {
	link := &fakeLink{}
	withFakeBackend(t, &fakeBackend{link: link, adverts: []Advert{{Address: "AA:BB:CC:DD:EE:FF", RSSI: -40}}})

	result, err := NewLiveTransport("", 2*time.Second).ExecuteCommand(
		context.Background(),
		CommandDefinition{Name: "probe", CharacteristicUUID: "ff01", PayloadHex: "01ff"},
		false,
	)
	if err != nil {
		t.Fatalf("ExecuteCommand: %v", err)
	}
	if result.Transport != "live" {
		t.Errorf("transport = %q, want live", result.Transport)
	}
	want, _ := hex.DecodeString("01ff")
	if got := link.writes["ff01"]; string(got) != string(want) {
		t.Errorf("wrote %x to ff01, want %x", got, want)
	}
	if !link.closed {
		t.Error("link was not closed")
	}
}

func TestLiveTransportDryRunDoesNotWrite(t *testing.T) {
	link := &fakeLink{}
	withFakeBackend(t, &fakeBackend{link: link})

	result, err := NewLiveTransport("AA:BB:CC:DD:EE:FF", 2*time.Second).ExecuteCommand(
		context.Background(),
		CommandDefinition{Name: "probe", CharacteristicUUID: "ff01", PayloadHex: "01ff"},
		true,
	)
	if err != nil {
		t.Fatalf("ExecuteCommand: %v", err)
	}
	if !result.DryRun {
		t.Error("expected a dry-run result")
	}
	if len(link.writes) != 0 {
		t.Errorf("dry-run wrote to the device: %v", link.writes)
	}
}

func TestLiveTransportScanSortsByRSSI(t *testing.T) {
	withFakeBackend(t, &fakeBackend{adverts: []Advert{{Address: "weak", RSSI: -80}, {Address: "strong", RSSI: -30}}})

	adverts, err := NewLiveTransport("", 2*time.Second).Scan(context.Background())
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(adverts) != 2 || adverts[0].Address != "strong" {
		t.Errorf("scan not sorted strongest-first: %+v", adverts)
	}
}
