// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"encoding/hex"
	"fmt"
	"time"

	"ble-temperature-sensor-pp-cli/internal/cliutil"
)

// LiveTransport drives the device over a real BLE connection (when the binary is
// built with -tags ble_live). It implements Transport, so the same commands that
// replay evidence by default actuate hardware under --live. Without the build
// tag, every operation returns ErrLiveUnavailable.
type LiveTransport struct {
	address string
	timeout time.Duration
}

func NewLiveTransport(address string, timeout time.Duration) *LiveTransport {
	if timeout <= 0 {
		timeout = 20 * time.Second
	}
	return &LiveTransport{address: address, timeout: timeout}
}

// opContext bounds an operation by the configured timeout, curtailed under the
// live-dogfood matrix so a single connect+op fits the runner's per-command cap.
func (t *LiveTransport) opContext(parent context.Context) (context.Context, context.CancelFunc) {
	timeout := t.timeout
	if cliutil.IsDogfoodEnv() && timeout > 5*time.Second {
		timeout = 5 * time.Second
	}
	return context.WithTimeout(parent, timeout)
}

func (t *LiveTransport) Status(ctx context.Context) (StatusSnapshot, error) {
	if cliutil.IsVerifyEnv() {
		return StatusSnapshot{Device: DisplayName, Transport: "verify-live-noop", SessionMode: SessionMode, ObservedAt: nowUTC(), Telemetry: map[string]any{}}, nil
	}
	ctx, cancel := t.opContext(ctx)
	defer cancel()
	telemetry := map[string]any{}
	err := t.withLink(ctx, func(l bleLink) error {
		for _, field := range StatusFields {
			entry := map[string]any{"source_characteristic_uuid": field.SourceCharacteristicUUID}
			raw, readErr := l.Read(field.SourceCharacteristicUUID)
			if readErr != nil {
				// Readable characteristics surface a value directly; notify-only
				// vendor telemetry needs a codec, so report why it is empty.
				entry["error"] = readErr.Error()
			} else {
				entry["raw_hex"] = hex.EncodeToString(raw)
			}
			telemetry[field.Name] = entry
		}
		return nil
	})
	if err != nil {
		return StatusSnapshot{}, err
	}
	return StatusSnapshot{Device: DisplayName, Transport: "live", SessionMode: SessionMode, ObservedAt: nowUTC(), Telemetry: telemetry}, nil
}

func (t *LiveTransport) ExecuteCommand(ctx context.Context, command CommandDefinition, dryRun bool) (CommandResult, error) {
	if cliutil.IsVerifyEnv() {
		return CommandResult{Command: command.Name, Transport: "verify-live-noop", CharacteristicUUID: command.CharacteristicUUID, PayloadHex: command.PayloadHex, Safety: command.Safety, ValidationStatus: command.ValidationStatus, DryRun: true, VerifyNoop: true, Reason: "verify_short_circuit"}, nil
	}
	if dryRun {
		return CommandResult{Command: command.Name, Transport: "live", CharacteristicUUID: command.CharacteristicUUID, PayloadHex: command.PayloadHex, Safety: command.Safety, ValidationStatus: command.ValidationStatus, DryRun: true}, nil
	}
	payload, err := hex.DecodeString(command.PayloadHex)
	if err != nil {
		return CommandResult{}, fmt.Errorf("decode payload %q: %w", command.PayloadHex, err)
	}
	ctx, cancel := t.opContext(ctx)
	defer cancel()
	if err := t.withLink(ctx, func(l bleLink) error {
		return l.Write(command.CharacteristicUUID, payload)
	}); err != nil {
		return CommandResult{}, err
	}
	return CommandResult{Command: command.Name, Transport: "live", CharacteristicUUID: command.CharacteristicUUID, PayloadHex: command.PayloadHex, Safety: command.Safety, ValidationStatus: command.ValidationStatus}, nil
}

// Scan discovers nearby devices that expose the device's BLE service(s).
func (t *LiveTransport) Scan(ctx context.Context) ([]Advert, error) {
	if cliutil.IsVerifyEnv() {
		return nil, nil
	}
	be, err := newBLEBackend()
	if err != nil {
		return nil, err
	}
	ctx, cancel := t.opContext(ctx)
	defer cancel()
	adverts, err := be.Scan(ctx, ServiceUUIDs)
	if err != nil {
		return nil, err
	}
	sortByRSSI(adverts)
	return adverts, nil
}

// withLink scans for the device by its service UUIDs (unless an explicit address
// was given), connects, runs fn against the link, then disconnects.
func (t *LiveTransport) withLink(ctx context.Context, fn func(bleLink) error) error {
	be, err := newBLEBackend()
	if err != nil {
		return err
	}
	address := t.address
	if address == "" {
		adverts, err := be.Scan(ctx, ServiceUUIDs)
		if err != nil {
			return err
		}
		sortByRSSI(adverts)
		if len(adverts) == 0 {
			return ErrDeviceNotFound
		}
		address = adverts[0].Address
	}
	l, err := be.Connect(ctx, address, ServiceUUIDs)
	if err != nil {
		return err
	}
	defer func() { _ = l.Close() }()
	return fn(l)
}

func nowUTC() string { return time.Now().UTC().Format(time.RFC3339) }

func sortByRSSI(adverts []Advert) {
	// Strongest (highest, closest to 0) RSSI first. Small slices; insertion sort
	// avoids importing sort for one call.
	for i := 1; i < len(adverts); i++ {
		for j := i; j > 0 && adverts[j].RSSI > adverts[j-1].RSSI; j-- {
			adverts[j], adverts[j-1] = adverts[j-1], adverts[j]
		}
	}
}
