// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

const (
	Name                   = "ble-temperature-sensor"
	DisplayName            = "BLE Temperature Sensor"
	Protocol               = "ble"
	SessionMode            = "one-shot"
	SessionOneShotFallback = false
)

type StatusField struct {
	Name                     string `json:"name"`
	SourceCharacteristicUUID string `json:"source_characteristic_uuid"`
	Unit                     string `json:"unit,omitempty"`
	SampleCadence            string `json:"sample_cadence,omitempty"`
	Store                    bool   `json:"store,omitempty"`
}

var StatusFields = []StatusField{
	{Name: "temperature", SourceCharacteristicUUID: "2a6e", Unit: "celsius", SampleCadence: "notification", Store: false},
}
