// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"strings"
	"testing"
)

// TestFilterFields_EnvelopeUnwrap_DropsHeavyEnvelopeField covers the dominant
// token-saving case: RPC-style POST responses that wrap items in a common
// envelope key alongside a heavy companion field (full context blobs, raw
// prose, etc.). --select with item-level fields should descend into the
// array and drop the heavy envelope companion.
func TestFilterFields_EnvelopeUnwrap_DropsHeavyEnvelopeField(t *testing.T) {
	t.Parallel()
	in := json.RawMessage(`{
		"results": [
			{"id":"a","score":0.5,"content":"long body 1"},
			{"id":"b","score":0.3,"content":"long body 2"}
		],
		"context": "THIS IS A 3KB PREFETCHED BLOB THAT --SELECT SHOULD STRIP",
		"token_estimate": 544
	}`)
	out := filterFields(in, "id,score")

	var arr []map[string]any
	if err := json.Unmarshal(out, &arr); err != nil {
		t.Fatalf("expected array after envelope unwrap, got %s (err=%v)", out, err)
	}
	if len(arr) != 2 {
		t.Fatalf("expected 2 items, got %d", len(arr))
	}
	for i, item := range arr {
		if _, ok := item["id"]; !ok {
			t.Errorf("item %d missing id: %v", i, item)
		}
		if _, ok := item["score"]; !ok {
			t.Errorf("item %d missing score: %v", i, item)
		}
		if _, ok := item["content"]; ok {
			t.Errorf("item %d should not contain content: %v", i, item)
		}
	}
	if strings.Contains(string(out), "PREFETCHED BLOB") {
		t.Errorf("envelope's context field should be dropped, got: %s", out)
	}
	if strings.Contains(string(out), "token_estimate") {
		t.Errorf("envelope companion fields should be dropped, got: %s", out)
	}
}

// TestFilterFields_DottedPath_PreservesEnvelopeWrap covers the escape hatch:
// when a user wants the envelope wrap preserved, dotted paths
// (results.id, results.score) keep the object shape AND narrow array items.
func TestFilterFields_DottedPath_PreservesEnvelopeWrap(t *testing.T) {
	t.Parallel()
	in := json.RawMessage(`{
		"results": [{"id":"a","score":0.5,"content":"long"}],
		"context": "heavy"
	}`)
	out := filterFields(in, "results.id,results.score")

	var obj map[string]json.RawMessage
	if err := json.Unmarshal(out, &obj); err != nil {
		t.Fatalf("expected object (envelope preserved), got %s (err=%v)", out, err)
	}
	if _, ok := obj["results"]; !ok {
		t.Fatalf("expected results envelope preserved, got: %s", out)
	}
	if _, ok := obj["context"]; ok {
		t.Errorf("non-selected envelope fields should be dropped, got: %s", out)
	}
}

// TestFilterFields_TopLevelMatch_DoesNotUnwrap covers the no-unwrap case: when
// a selected path matches a top-level key on an object response, --select
// behaves like the pre-envelope-unwrap logic (no descent into nested arrays).
func TestFilterFields_TopLevelMatch_DoesNotUnwrap(t *testing.T) {
	t.Parallel()
	in := json.RawMessage(`{
		"results": [{"id":"a"}],
		"total": 1,
		"context": "heavy"
	}`)
	out := filterFields(in, "total")

	var obj map[string]json.RawMessage
	if err := json.Unmarshal(out, &obj); err != nil {
		t.Fatalf("expected object (no unwrap because total matched top-level), got %s (err=%v)", out, err)
	}
	if _, ok := obj["total"]; !ok {
		t.Errorf("expected total in output, got: %s", out)
	}
	if _, ok := obj["results"]; ok {
		t.Errorf("results not selected; should be dropped, got: %s", out)
	}
}

// TestFilterFields_NoEnvelopeKey_FallsBackToObjectFilter covers the safety
// case: when no common envelope key (results/data/items/hits) is present,
// the function falls back to the pre-existing object-filtering behavior
// rather than unwrapping a random array-valued field.
func TestFilterFields_NoEnvelopeKey_FallsBackToObjectFilter(t *testing.T) {
	t.Parallel()
	in := json.RawMessage(`{
		"records": [{"id":"a","name":"alpha"}],
		"count": 1
	}`)
	out := filterFields(in, "id,name")

	// Path heads (id, name) don't match top-level keys (records, count), AND
	// "records" is not a recognized envelope key. Should NOT unwrap; pre-existing
	// behavior strips all non-matching top-level keys.
	if !strings.HasPrefix(strings.TrimSpace(string(out)), "{") {
		t.Errorf("expected object shape preserved when no envelope key matches, got: %s", out)
	}
}

// TestFilterFields_DataEnvelope_UnwrapsAndNarrows asserts the four recognized
// envelope keys (results, data, items, hits) all trigger the unwrap.
func TestFilterFields_DataEnvelope_UnwrapsAndNarrows(t *testing.T) {
	t.Parallel()
	for _, envelope := range []string{"results", "data", "items", "hits"} {
		envelope := envelope
		t.Run(envelope, func(t *testing.T) {
			t.Parallel()
			in := json.RawMessage(`{"` + envelope + `":[{"id":"x","extra":"y"}],"meta":"drop-me"}`)
			out := filterFields(in, "id")
			var arr []map[string]any
			if err := json.Unmarshal(out, &arr); err != nil {
				t.Fatalf("envelope %q: expected array after unwrap, got %s (err=%v)", envelope, out, err)
			}
			if len(arr) != 1 || arr[0]["id"] != "x" {
				t.Fatalf("envelope %q: expected [{id:x}], got %s", envelope, out)
			}
			if _, ok := arr[0]["extra"]; ok {
				t.Errorf("envelope %q: extra field not selected; should be stripped", envelope)
			}
		})
	}
}
