//go:build !linux && !windows && !(darwin && (amd64 || arm64))

// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Code generated by CLI Printing Press. DO NOT EDIT.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

// claimClosedStore cannot show that the source database is closed on this
// OS, so adoption waits for a later run instead of linking a live file.
func claimClosedStore(string) (func(), func() bool, bool) {
	return nil, nil, false
}
