//go:build darwin && (amd64 || arm64)

// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Code generated by CLI Printing Press. DO NOT EDIT.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"os"
	"unsafe"

	"golang.org/x/sys/unix"
)

const (
	darwinProcInfoListPIDs   = 1
	darwinProcInfoPIDInfo    = 2
	darwinProcInfoPIDFDInfo  = 3
	darwinProcAllPIDs        = 1
	darwinProcPIDListFDs     = 1
	darwinProcPIDFDVnodePath = 2
	darwinProxFDTypeVnode    = 1
	darwinMaxPathLen         = 1024
)

// Layout matches struct vnode_fdinfowithpath in bsd/sys/proc_info.h on LP64.
// A scan that cannot read this process's own descriptor fails closed.

type darwinVinfoStat struct {
	Dev     uint32
	Mode    uint16
	Nlink   uint16
	Ino     uint64
	Uid     uint32
	Gid     uint32
	Atime   int64
	AtimeN  int64
	Mtime   int64
	MtimeN  int64
	Ctime   int64
	CtimeN  int64
	Birth   int64
	BirthN  int64
	Size    int64
	Blocks  int64
	Blksize int32
	Flags   uint32
	Gen     uint32
	Rdev    uint32
	Qspare  [2]int64
}

type darwinFsid struct {
	Val [2]int32
}

type darwinVnodeInfo struct {
	Stat darwinVinfoStat
	Type int32
	Pad  int32
	Fsid darwinFsid
}

type darwinVnodeInfoPath struct {
	Vi   darwinVnodeInfo
	Path [darwinMaxPathLen]byte
}

type darwinProcFileInfo struct {
	Openflags  uint32
	Status     uint32
	Offset     int64
	Type       int32
	Guardflags uint32
}

type darwinVnodeFDInfoWithPath struct {
	Pfi  darwinProcFileInfo
	Pvip darwinVnodeInfoPath
}

type darwinProcFDInfo struct {
	Fd   int32
	Type uint32
}

func claimClosedStore(legacy string) (func(), func() bool, bool) {
	paths, ok := legacyStoreAdoptPaths(legacy)
	if !ok {
		return nil, nil, false
	}
	files := make([]*os.File, 0, len(paths))
	release := func() {
		for i := len(files) - 1; i >= 0; i-- {
			_ = files[i].Close()
		}
	}
	for _, path := range paths {
		f, err := os.Open(path)
		if err != nil {
			release()
			return nil, nil, false
		}
		files = append(files, f)
		if !darwinStoreFileUnusedByOthers(f) {
			release()
			return nil, nil, false
		}
	}
	stillClosed := func() bool {
		for _, f := range files {
			if !darwinStoreFileUnusedByOthers(f) {
				return false
			}
		}
		return true
	}
	return release, stillClosed, true
}

func darwinStoreFileUnusedByOthers(f *os.File) bool {
	var self unix.Stat_t
	fd := int(f.Fd())
	if err := unix.Fstat(fd, &self); err != nil {
		return false
	}
	ownerOnly := self.Mode&0o077 == 0
	pids, ok := darwinPIDs()
	if !ok {
		return false
	}
	selfPID := os.Getpid()
	sawSelf := false
	for _, pid := range pids {
		if pid <= 0 {
			continue
		}
		fds, fdsOK := darwinFDs(int(pid))
		if !fdsOK {
			if int(pid) == selfPID {
				return false
			}
			if !ownerOnly {
				return false
			}
			continue
		}
		for _, info := range fds {
			if info.Type != darwinProxFDTypeVnode {
				continue
			}
			ino, dev, got := darwinVnodeID(int(pid), info.Fd)
			if int(pid) == selfPID && int(info.Fd) == fd {
				if !got || ino != self.Ino || dev != uint32(self.Dev) {
					return false
				}
				sawSelf = true
				continue
			}
			if !got {
				if int(pid) == selfPID {
					return false
				}
				continue
			}
			if ino == self.Ino && dev == uint32(self.Dev) {
				return false
			}
		}
	}
	return sawSelf
}

func darwinPIDs() ([]int32, bool) {
	n := 1024
	for n < 1<<20 {
		buf := make([]int32, n)
		got, err := darwinProcInfo(darwinProcInfoListPIDs, darwinProcAllPIDs, 0, 0, unsafe.Pointer(&buf[0]), n*4)
		if err != nil {
			return nil, false
		}
		count := got / 4
		if count < n {
			return buf[:count], true
		}
		n *= 2
	}
	return nil, false
}

func darwinFDs(pid int) ([]darwinProcFDInfo, bool) {
	size := int(unsafe.Sizeof(darwinProcFDInfo{}))
	n := 64
	for n < 1<<20 {
		buf := make([]darwinProcFDInfo, n)
		got, err := darwinProcInfo(darwinProcInfoPIDInfo, pid, darwinProcPIDListFDs, 0, unsafe.Pointer(&buf[0]), n*size)
		if err != nil {
			return nil, false
		}
		count := got / size
		if count < n {
			return buf[:count], true
		}
		n *= 2
	}
	return nil, false
}

func darwinVnodeID(pid int, fd int32) (uint64, uint32, bool) {
	var info darwinVnodeFDInfoWithPath
	n, err := darwinProcInfo(darwinProcInfoPIDFDInfo, pid, darwinProcPIDFDVnodePath, uint64(fd), unsafe.Pointer(&info), int(unsafe.Sizeof(info)))
	if err != nil || n < int(unsafe.Sizeof(info)) {
		return 0, 0, false
	}
	return info.Pvip.Vi.Stat.Ino, info.Pvip.Vi.Stat.Dev, true
}

func darwinProcInfo(call, pid, flavor int, arg uint64, buf unsafe.Pointer, size int) (int, error) {
	r1, _, errno := unix.Syscall6(
		unix.SYS_PROC_INFO,
		uintptr(call),
		uintptr(pid),
		uintptr(flavor),
		uintptr(arg),
		uintptr(buf),
		uintptr(size),
	)
	if errno != 0 {
		return 0, errno
	}
	return int(r1), nil
}
