//go:build linux

// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Code generated by CLI Printing Press. DO NOT EDIT.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"golang.org/x/sys/unix"
)

// claimClosedStore pins legacy and its sidecars so they can be published only
// while no other process has them open. A write lease fails when any other
// descriptor has the file, including an idle SQLite connection between
// transactions, and blocks new opens until release. Kernels with leases
// disabled fall back to a descriptor scan and skip the move when that scan
// cannot show the file is unused.
func claimClosedStore(legacy string) (func(), func() bool, bool) {
	paths, ok := legacyStoreAdoptPaths(legacy)
	if !ok {
		return nil, nil, false
	}
	pins := make([]storeFilePin, 0, len(paths))
	release := func() {
		for i := len(pins) - 1; i >= 0; i-- {
			pins[i].close()
		}
	}
	for _, path := range paths {
		pin, pinned := pinClosedStoreFile(path)
		if !pinned {
			release()
			return nil, nil, false
		}
		pins = append(pins, pin)
	}
	stillClosed := func() bool {
		for _, pin := range pins {
			if !pin.stillClosed() {
				return false
			}
		}
		return true
	}
	if !stillClosed() {
		release()
		return nil, nil, false
	}
	return release, stillClosed, true
}

type storeFilePin struct {
	f      *os.File
	leased bool
}

func (p storeFilePin) close() {
	if p.f == nil {
		return
	}
	if p.leased {
		_, _ = unix.FcntlInt(p.f.Fd(), unix.F_SETLEASE, unix.F_UNLCK)
	}
	_ = p.f.Close()
}

func (p storeFilePin) stillClosed() bool {
	if p.leased {
		return true
	}
	return storeFileUnusedByOthers(p.f)
}

func pinClosedStoreFile(path string) (storeFilePin, bool) {
	f, err := os.OpenFile(path, os.O_RDWR, 0)
	if err != nil {
		f, err = os.Open(path)
		if err != nil {
			return storeFilePin{}, false
		}
		if !storeFileUnusedByOthers(f) {
			_ = f.Close()
			return storeFilePin{}, false
		}
		return storeFilePin{f: f}, true
	}
	if _, err := unix.FcntlInt(f.Fd(), unix.F_SETLEASE, unix.F_WRLCK); err == nil {
		return storeFilePin{f: f, leased: true}, true
	}
	if !storeFileUnusedByOthers(f) {
		_ = f.Close()
		return storeFilePin{}, false
	}
	return storeFilePin{f: f}, true
}

func storeFileUnusedByOthers(f *os.File) bool {
	var self unix.Stat_t
	fd := int(f.Fd())
	if err := unix.Fstat(fd, &self); err != nil {
		return false
	}
	selfPath := filepath.Join("/proc/self/fd", strconv.Itoa(fd))
	var viaProc unix.Stat_t
	if err := unix.Stat(selfPath, &viaProc); err != nil || viaProc.Dev != self.Dev || viaProc.Ino != self.Ino {
		return false
	}
	ownerOnly := self.Mode&0o077 == 0
	entries, err := os.ReadDir("/proc")
	if err != nil {
		return false
	}
	selfPID := os.Getpid()
	claimFD := strconv.Itoa(fd)
	for _, ent := range entries {
		pid, convErr := strconv.Atoi(ent.Name())
		if convErr != nil {
			continue
		}
		fdDir := filepath.Join("/proc", ent.Name(), "fd")
		fds, readErr := os.ReadDir(fdDir)
		if readErr != nil {
			// A disabled lease and a busy file return the same error, so this
			// scan has to see descriptors in this process too. Skipping them
			// would publish a database this process already has open.
			if pid == selfPID || !ownerOnly || procSameUID(pid) {
				return false
			}
			continue
		}
		for _, fdEnt := range fds {
			if pid == selfPID && fdEnt.Name() == claimFD {
				continue
			}
			var st unix.Stat_t
			if err := unix.Stat(filepath.Join(fdDir, fdEnt.Name()), &st); err != nil {
				if pid == selfPID {
					return false
				}
				continue
			}
			if st.Dev == self.Dev && st.Ino == self.Ino {
				return false
			}
		}
	}
	return true
}

func procSameUID(pid int) bool {
	data, err := os.ReadFile(filepath.Join("/proc", strconv.Itoa(pid), "status"))
	if err != nil {
		return true
	}
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "Uid:") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			return true
		}
		uid, convErr := strconv.Atoi(fields[1])
		if convErr != nil {
			return true
		}
		return uid == os.Getuid()
	}
	return true
}
