package generator

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"

	"github.com/mvanhorn/cli-printing-press/v4/internal/devicespec"
	"github.com/mvanhorn/cli-printing-press/v4/internal/naming"
)

type DeviceGenerator struct {
	Spec      *devicespec.DeviceSpec
	OutputDir string
}

type deviceTemplateData struct {
	Spec         *devicespec.DeviceSpec
	Name         string
	CLIName      string
	ModulePath   string
	DisplayName  string
	CurrentYear  int
	StatusFields []deviceStatusField
	Commands     []deviceCommandField
	HasCommands  bool
	HasSession   bool
}

type deviceStatusField struct {
	Name               string
	CharacteristicUUID string
	Unit               string
	SampleCadence      string
	Store              bool
}

type deviceCommandField struct {
	Name               string
	CharacteristicUUID string
	Safety             string
	ValidationStatus   string
	PayloadHex         string
}

func NewDevice(spec *devicespec.DeviceSpec, outputDir string) *DeviceGenerator {
	return &DeviceGenerator{Spec: spec, OutputDir: outputDir}
}

func (g *DeviceGenerator) Generate() error {
	if g.Spec == nil {
		return fmt.Errorf("device spec is required")
	}
	if err := g.Spec.Validate(); err != nil {
		return err
	}
	data := g.templateData()
	files := map[string]string{
		"go.mod": deviceGoModTemplate,
		filepath.Join("cmd", data.CLIName, "main.go"):       deviceMainTemplate,
		filepath.Join("internal", "cli", "root.go"):         deviceRootTemplate,
		filepath.Join("internal", "device", "spec.go"):      deviceSpecTemplate,
		filepath.Join("internal", "device", "transport.go"): deviceTransportTemplate,
		"README.md": deviceReadmeTemplate,
		"SKILL.md":  deviceSkillTemplate,
	}
	if data.HasSession {
		files[filepath.Join("internal", "device", "session.go")] = deviceSessionTemplate
	}
	for path, tmpl := range files {
		if err := g.render(path, tmpl, data); err != nil {
			return err
		}
	}
	return nil
}

func (g *DeviceGenerator) Validate() error {
	if _, err := runCommand(g.OutputDir, qualityGateTimeout, "go", "mod", "tidy"); err != nil {
		return fmt.Errorf("go mod tidy: %w", err)
	}
	if _, err := runCommand(g.OutputDir, qualityGateTimeout, "go", "build", "./..."); err != nil {
		return fmt.Errorf("go build ./...: %w", err)
	}
	return nil
}

func (g *DeviceGenerator) templateData() deviceTemplateData {
	name := g.Spec.Name
	displayName := g.Spec.DisplayName
	if displayName == "" {
		displayName = naming.HumanName(name)
	}
	statusFields := make([]deviceStatusField, 0, len(g.Spec.Capabilities.Telemetry))
	for _, field := range g.Spec.Capabilities.Telemetry {
		statusFields = append(statusFields, deviceStatusField{
			Name:               field.Name,
			CharacteristicUUID: field.SourceCharacteristicUUID,
			Unit:               field.Unit,
			SampleCadence:      field.SampleCadence,
			Store:              field.Store,
		})
	}
	commands := make([]deviceCommandField, 0, len(g.Spec.Capabilities.Commands))
	for _, command := range g.Spec.Capabilities.Commands {
		if command.Safety != devicespec.SafetyLowRiskWrite {
			continue
		}
		commands = append(commands, deviceCommandField{
			Name:               naming.FlagName(command.Name),
			CharacteristicUUID: command.CharacteristicUUID,
			Safety:             command.Safety,
			ValidationStatus:   command.ValidationStatus,
			PayloadHex:         hex.EncodeToString(command.Payload.Bytes),
		})
	}
	return deviceTemplateData{
		Spec:         g.Spec,
		Name:         name,
		CLIName:      naming.CLI(name),
		ModulePath:   naming.CLI(name),
		DisplayName:  displayName,
		CurrentYear:  time.Now().Year(),
		StatusFields: statusFields,
		Commands:     commands,
		HasCommands:  len(commands) > 0,
		HasSession:   g.Spec.Session.Mode == devicespec.SessionModeOptional || g.Spec.Session.Mode == devicespec.SessionModeRequired,
	}
}

func (g *DeviceGenerator) render(relPath, tmplText string, data deviceTemplateData) error {
	tmpl, err := template.New(relPath).Funcs(template.FuncMap{
		"quote": func(value string) string { return fmt.Sprintf("%q", value) },
	}).Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse %s template: %w", relPath, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render %s: %w", relPath, err)
	}
	path := filepath.Join(g.OutputDir, relPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, normalizeRendered(buf.Bytes(), relPath, relPath), 0o644)
}

const deviceGoModTemplate = `module {{.ModulePath}}

go 1.26.3

require github.com/spf13/cobra v1.9.1
`

const deviceMainTemplate = `// Copyright {{.CurrentYear}}. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"os"

	"{{.ModulePath}}/internal/cli"
)

func main() {
	if err := cli.Execute(); err != nil {
		os.Exit(cli.ExitCode(err))
	}
}
`

const deviceRootTemplate = `// Copyright {{.CurrentYear}}. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"

	"{{.ModulePath}}/internal/device"
	"github.com/spf13/cobra"
)

type rootFlags struct {
	asJSON bool
{{- if .HasCommands}}
	dryRun bool
{{- end}}
}

func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

func Execute() error {
	return RootCmd().Execute()
}

func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	return 1
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:          "{{.CLIName}}",
		Short:        "Control {{.DisplayName}} over BLE",
		Long:         "Control {{.DisplayName}} over BLE using a generated device-native CLI surface.",
		SilenceUsage: true,
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "agent", false, "Output agent-friendly JSON")
{{- if .HasCommands}}
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Preview device writes without dispatching them")
{{- end}}
	rootCmd.AddCommand(newStatusCmd(flags, device.NewReplayTransport()))
{{- if .HasSession}}
	rootCmd.AddCommand(newSessionCmd(flags, device.NewReplaySession()))
{{- end}}
{{- range .Commands}}
	rootCmd.AddCommand(newDeviceCommandCmd(flags, device.NewReplayTransport(), device.CommandDefinition{Name: {{quote .Name}}, CharacteristicUUID: {{quote .CharacteristicUUID}}, Safety: {{quote .Safety}}, ValidationStatus: {{quote .ValidationStatus}}, PayloadHex: {{quote .PayloadHex}}}))
{{- end}}
	return rootCmd
}

func newStatusCmd(flags *rootFlags, transport device.Transport) *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Read replay-backed device status",
		RunE: func(cmd *cobra.Command, args []string) error {
			snapshot, err := transport.Status(cmd.Context())
			if err != nil {
				return err
			}
			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(snapshot)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "%s status\n", snapshot.Device)
			fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", snapshot.Transport)
			fmt.Fprintf(cmd.OutOrStdout(), "session: %s\n", snapshot.SessionMode)
			for _, field := range device.StatusFields {
				value := snapshot.Telemetry[field.Name]
				fmt.Fprintf(cmd.OutOrStdout(), "%s: %v\n", field.Name, value)
			}
			return nil
		},
	}
}

{{ if .HasCommands}}
func newDeviceCommandCmd(flags *rootFlags, transport device.Transport, definition device.CommandDefinition) *cobra.Command {
	return &cobra.Command{
		Use:   definition.Name,
		Short: fmt.Sprintf("Replay %s against the device transport", definition.Name),
		RunE: func(cmd *cobra.Command, args []string) error {
			result, err := transport.ExecuteCommand(cmd.Context(), definition, flags.dryRun)
			if err != nil {
				return err
			}
			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(result)
			}
			if result.DryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "would write %s to %s for %s\n", result.PayloadHex, result.CharacteristicUUID, result.Command)
				return nil
			}
			fmt.Fprintf(cmd.OutOrStdout(), "replayed %s via %s\n", result.Command, result.Transport)
			return nil
		},
	}
}

{{ end}}
{{ if .HasSession}}
func newSessionCmd(flags *rootFlags, session device.Session) *cobra.Command {
	sessionCmd := &cobra.Command{
		Use:   "session",
		Short: "Inspect the replay-backed BLE session scaffold",
	}
	sessionCmd.AddCommand(newSessionStatusCmd(flags, session))
	sessionCmd.AddCommand(newSessionStartCmd(flags, session))
	sessionCmd.AddCommand(newSessionStopCmd(flags, session))
	return sessionCmd
}

func newSessionStatusCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show generated BLE session requirements",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Status(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStartCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "start",
		Short: "Start a replay BLE session placeholder",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Start(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func newSessionStopCmd(flags *rootFlags, session device.Session) *cobra.Command {
	return &cobra.Command{
		Use:   "stop",
		Short: "Stop a replay BLE session placeholder",
		RunE: func(cmd *cobra.Command, args []string) error {
			status, err := session.Stop(cmd.Context())
			if err != nil {
				return err
			}
			return writeSessionStatus(cmd, flags, status)
		},
	}
}

func writeSessionStatus(cmd *cobra.Command, flags *rootFlags, status device.SessionStatus) error {
	if flags.asJSON {
		enc := json.NewEncoder(cmd.OutOrStdout())
		enc.SetIndent("", "  ")
		return enc.Encode(status)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "%s session\n", status.Device)
	fmt.Fprintf(cmd.OutOrStdout(), "state: %s\n", status.State)
	fmt.Fprintf(cmd.OutOrStdout(), "mode: %s\n", status.Mode)
	fmt.Fprintf(cmd.OutOrStdout(), "transport: %s\n", status.Transport)
	fmt.Fprintf(cmd.OutOrStdout(), "one-shot fallback: %v\n", status.OneShotFallback)
	fmt.Fprintf(cmd.OutOrStdout(), "reconnect: %v\n", status.Reconnect)
	fmt.Fprintf(cmd.OutOrStdout(), "notification stream: %v\n", status.NotificationStream)
	for _, reason := range status.Reasons {
		fmt.Fprintf(cmd.OutOrStdout(), "reason: %s\n", reason)
	}
	if status.Detail != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "detail: %s\n", status.Detail)
	}
	return nil
}

{{ end}}
func ExecuteWithContext(ctx context.Context) error {
	cmd := RootCmd()
	cmd.SetContext(ctx)
	return cmd.Execute()
}
`

const deviceSpecTemplate = `// Copyright {{.CurrentYear}}. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

const (
	Name                = {{quote .Name}}
	DisplayName         = {{quote .DisplayName}}
	Protocol            = "ble"
	SessionMode         = {{quote .Spec.Session.Mode}}
	SessionOneShotFallback = {{if .Spec.Session.OneShotFallback}}true{{else}}false{{end}}
{{- if .HasSession}}
	SessionReconnect = {{if .Spec.Session.Reconnect}}true{{else}}false{{end}}
	SessionNotificationStream = {{if .Spec.Session.NotificationStream}}true{{else}}false{{end}}
{{- end}}
)

{{- if .HasSession}}
var SessionReasons = []string{
{{- range .Spec.Session.Reasons}}
	{{quote .}},
{{- end}}
}
{{- end}}

type StatusField struct {
	Name                     string ` + "`json:\"name\"`" + `
	SourceCharacteristicUUID string ` + "`json:\"source_characteristic_uuid\"`" + `
	Unit                     string ` + "`json:\"unit,omitempty\"`" + `
	SampleCadence            string ` + "`json:\"sample_cadence,omitempty\"`" + `
	Store                    bool   ` + "`json:\"store,omitempty\"`" + `
}

var StatusFields = []StatusField{
{{- range .StatusFields}}
	{Name: {{quote .Name}}, SourceCharacteristicUUID: {{quote .CharacteristicUUID}}, Unit: {{quote .Unit}}, SampleCadence: {{quote .SampleCadence}}, Store: {{if .Store}}true{{else}}false{{end}}},
{{- end}}
}

type CommandDefinition struct {
	Name               string ` + "`json:\"name\"`" + `
	CharacteristicUUID string ` + "`json:\"characteristic_uuid\"`" + `
	Safety             string ` + "`json:\"safety\"`" + `
	ValidationStatus   string ` + "`json:\"validation_status,omitempty\"`" + `
	PayloadHex         string ` + "`json:\"payload_hex\"`" + `
}

var CommandDefinitions = []CommandDefinition{
{{- range .Commands}}
	{Name: {{quote .Name}}, CharacteristicUUID: {{quote .CharacteristicUUID}}, Safety: {{quote .Safety}}, ValidationStatus: {{quote .ValidationStatus}}, PayloadHex: {{quote .PayloadHex}}},
{{- end}}
}
`

const deviceTransportTemplate = `// Copyright {{.CurrentYear}}. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"time"
)

type StatusSnapshot struct {
	Device      string         ` + "`json:\"device\"`" + `
	Transport   string         ` + "`json:\"transport\"`" + `
	SessionMode string         ` + "`json:\"session_mode\"`" + `
	ObservedAt  string         ` + "`json:\"observed_at\"`" + `
	Telemetry   map[string]any ` + "`json:\"telemetry\"`" + `
}

type CommandResult struct {
	Command            string ` + "`json:\"command\"`" + `
	Transport          string ` + "`json:\"transport\"`" + `
	CharacteristicUUID string ` + "`json:\"characteristic_uuid\"`" + `
	PayloadHex         string ` + "`json:\"payload_hex\"`" + `
	Safety             string ` + "`json:\"safety\"`" + `
	ValidationStatus   string ` + "`json:\"validation_status,omitempty\"`" + `
	DryRun             bool   ` + "`json:\"dry_run\"`" + `
}

type Transport interface {
	Status(context.Context) (StatusSnapshot, error)
	ExecuteCommand(context.Context, CommandDefinition, bool) (CommandResult, error)
}

type ReplayTransport struct{}

func NewReplayTransport() *ReplayTransport {
	return &ReplayTransport{}
}

func (t *ReplayTransport) Status(ctx context.Context) (StatusSnapshot, error) {
	telemetry := map[string]any{}
	for _, field := range StatusFields {
		telemetry[field.Name] = map[string]any{
			"source_characteristic_uuid": field.SourceCharacteristicUUID,
			"sample_cadence":             field.SampleCadence,
			"value":                      nil,
		}
	}
	return StatusSnapshot{
		Device:      DisplayName,
		Transport:   "replay",
		SessionMode: SessionMode,
		ObservedAt:  time.Now().UTC().Format(time.RFC3339),
		Telemetry:   telemetry,
	}, nil
}

func (t *ReplayTransport) ExecuteCommand(ctx context.Context, command CommandDefinition, dryRun bool) (CommandResult, error) {
	return CommandResult{
		Command:            command.Name,
		Transport:          "replay",
		CharacteristicUUID: command.CharacteristicUUID,
		PayloadHex:         command.PayloadHex,
		Safety:             command.Safety,
		ValidationStatus:   command.ValidationStatus,
		DryRun:             dryRun,
	}, nil
}
`

const deviceSessionTemplate = `// Copyright {{.CurrentYear}}. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package device

import (
	"context"
	"time"
)

type SessionStatus struct {
	Device             string   ` + "`json:\"device\"`" + `
	Mode               string   ` + "`json:\"mode\"`" + `
	State              string   ` + "`json:\"state\"`" + `
	Transport          string   ` + "`json:\"transport\"`" + `
	ObservedAt         string   ` + "`json:\"observed_at\"`" + `
	Reasons            []string ` + "`json:\"reasons,omitempty\"`" + `
	OneShotFallback    bool     ` + "`json:\"one_shot_fallback\"`" + `
	Reconnect          bool     ` + "`json:\"reconnect\"`" + `
	NotificationStream bool     ` + "`json:\"notification_stream\"`" + `
	Detail             string   ` + "`json:\"detail,omitempty\"`" + `
}

type Session interface {
	Start(context.Context) (SessionStatus, error)
	Status(context.Context) (SessionStatus, error)
	Stop(context.Context) (SessionStatus, error)
}

type ReplaySession struct{}

func NewReplaySession() *ReplaySession {
	return &ReplaySession{}
}

func (s *ReplaySession) Start(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("started"), nil
}

func (s *ReplaySession) Status(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("not-running"), nil
}

func (s *ReplaySession) Stop(ctx context.Context) (SessionStatus, error) {
	return sessionStatus("stopped"), nil
}

func sessionStatus(state string) SessionStatus {
	return SessionStatus{
		Device:             DisplayName,
		Mode:               SessionMode,
		State:              state,
		Transport:          "replay",
		ObservedAt:         time.Now().UTC().Format(time.RFC3339),
		Reasons:            append([]string(nil), SessionReasons...),
		OneShotFallback:    SessionOneShotFallback,
		Reconnect:          SessionReconnect,
		NotificationStream: SessionNotificationStream,
		Detail:             "replay session scaffold only; live BLE IPC is not enabled in this generated CLI yet",
	}
}
`

const deviceReadmeTemplate = `# {{.DisplayName}} CLI

Generated by the Printing Press from a BLE device spec.

This CLI is device-native: commands refer to BLE device capabilities rather than HTTP endpoints. The first generated runtime uses replay transport so verification does not connect to or actuate a physical device.

## Commands

- ` + "`{{.CLIName}} status --json`" + ` prints replay-backed status fields.
{{- range .Commands}}
- ` + "`{{$.CLIName}} {{.Name}} --dry-run --json`" + ` previews the {{.Name}} BLE write.
{{- end}}
{{- if .HasSession}}
- ` + "`{{.CLIName}} session status --json`" + ` prints the generated session requirements and replay scaffold state.
{{- end}}
`

const deviceSkillTemplate = `---
name: {{.Name}}
description: Control {{.DisplayName}} through the generated BLE device CLI.
---

Use ` + "`{{.CLIName}} status --json`" + ` to inspect replay-backed status output.{{range .Commands}} Use ` + "`{{$.CLIName}} {{.Name}} --dry-run --json`" + ` to preview the {{.Name}} write.{{end}}{{if .HasSession}} Use ` + "`{{.CLIName}} session status --json`" + ` to inspect the generated session requirements before building live BLE IPC.{{else}} Live BLE control and optional session IPC are generated only when later device-session support is enabled by the device spec.{{end}}
`
